### ISSUE TITLE
Change color of send button

### ISSUE THREAD

**Issue by NielsRogge** [botfront/rasa-webchat#272]
How can I change the color of the send button (the arrow, which is blue by default)?

I tried adding this to the `style.css` file, but it did not change anything:
    
    .rw-conversation-container .rw-send-icon {
           color: black;
    }

**Comment by MatthieuJnon** [comment]
Hi, you have to change the `.rw-send-icon-ready` class using the `fill` css property since it's a svg path.

```css
.rw-send-icon-ready {
    fill: grey !important;
}
```
