### ISSUE TITLE
Issue with Docker compose

### ISSUE THREAD

**Issue by andrewlu0** [botfront/rasa-webchat#320]
Hi,
I am having an issue when separating my React app and Rasa server into two different Docker containers and building with docker compose. 
Here is my docker-compose.yml:
```
version: '3.0'

services:
  nginx:
    container_name: "nginx"
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on: 
      - rasa_server
      - action_server
      - assistant_ui
  
  duckling:
    image: rasa/duckling:latest
    ports:
    - "8000:8000"

  rasa_server:
    container_name: "rasa_server"
    build:
      context: .
    ports:
    - "5005:5005"
    expose: 
      - 5005
  
  action_server:
    container_name: "action_server"
    build:
      context: actions
    volumes:
      - ./actions:/app/actions
    ports:
    - "5055:5055"
  
  assistant_ui:
    container_name: "assistant_ui"
    build:
      context: front
    ports:
    - "3000:3000"
```

And here is my custom widget:
```
function CustomWidget (props) {
  return (
    <Widget
      initPayload={"/get_started"}
      socketUrl={"http://rasa_server:5005"}
      socketPath={"/socket.io/"}
      inputTextFieldHint={"Enter a valid command"}
      customData={{"language": "en"}} // arbitrary custom data. Stay minimal as this will be added to the socket
      title={"Virtual Assistant"}
      showFullScreenButton={"true"}
      embedded={"true"}
      hideWhenNotConnected = {"false"}
      params={{"storage": "session"}}
    />
  );
}
```

I can make pings to the rasa_server container from inside the assistant_ui container but when I open the web page, the chat box is not displayed.
