### ISSUE TITLE
Socket Version

### ISSUE THREAD

**Issue by nenads** [botfront/rasa-webchat#359]
Hi,

i am ruining botfront 1.05 with all versions that come with it
```
images:
  default:
    botfront: 'botfront/botfront:v1.0.5'
    rasa: 'botfront/rasa-for-botfront:v2.3.3-bf.3'
    duckling: 'botfront/duckling:latest'
    mongo: 'mongo:latest'
    actions: 'rasa/rasa-sdk:2.1.2'
  current:
    botfront: 'botfront/botfront:v1.0.5'
    rasa: 'botfront/rasa-for-botfront:v2.3.3-bf.3'
    duckling: 'botfront/duckling:latest'
    mongo: 'mongo:latest'
    actions: 'rasa/rasa-sdk:2.1.2'
```

What i have notices is that webchat client is trying to access 

https://my_server/socket.io/?EIO=3&transport=polling&t=NXZug2k where this is response
"The client is using an unsupported version of the Socket.IO or Engine.IO protocols"

if i change EIO=4 all is ok. 
0{"sid":"9qd4zgMgIyzZ-DbeAAAF","upgrades":["websocket"],"pingTimeout":5000,"pingInterval":25000}

Protocol 4 is used by botfront share chat so botfront works ok. My issue is usage of snippet

What is status of updating js socket version ?
Have tryed all diferent versions even the latest
https://cdn.jsdelivr.net/npm/rasa-webchat/lib/index.js
They all use Socket 3
