### ISSUE TITLE
Bot does not respond

### ISSUE THREAD

**Issue by caiolivf** [botfront/rasa-webchat#481]
Hi!

I'm creating a new Rasa project and when I try to interact with the bot via webchat, the bot doesn't respond.

![image](https://github.com/botfront/rasa-webchat/assets/106786010/2c89eb07-4c37-423e-a97a-d8add052e855)

I'm using the follow versions:
![image](https://github.com/botfront/rasa-webchat/assets/106786010/837ad71e-cc4f-48b1-9069-2ad3665ae986)

Does anyone have any idea what could cause this behavior?
Thanks!

**Comment by mumbaigirl** [comment]
@caiolivf You need to uncomment the following
```
socketio:
  user_message_evt: user_uttered
  bot_message_evt: bot_uttered
  session_persistence: true
```
Try session_persistence: false and give it a try, you need to manage sessions. Check [this ](https://rasa.com/docs/rasa/connectors/your-own-website/)
